sudo: false
dist: trusty
language: go
go:
  - "1.10"
  - master
install:
  - go get github.com/jehiah/go-strftime
  - go get github.com/ogier/pflag
  - go build tlog.go
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run
  - go test -v .
  - "{ echo first line; sleep .5; echo second line; } | ./tlog"
